from pathlib import Path

from dotenv import load_dotenv


BASE_DIR = Path(__file__).resolve().parent

# .env를 먼저 읽어 두면 다른 파일에서 환경변수를 쉽게 사용할 수 있습니다.
load_dotenv(BASE_DIR / ".env")

# OpenAI 설정
MODEL_NAME = "gpt-4o-mini"
MAX_OUTPUT_TOKENS = 800
OPENAI_API_KEY_ENV_NAME = "OPENAI_API_KEY"

# Oracle 설정
ORACLE_USER_ENV_NAME = "ORACLE_USER"
ORACLE_PASSWORD_ENV_NAME = "ORACLE_PASSWORD"
ORACLE_DSN_ENV_NAME = "ORACLE_DSN"
ORACLE_TNS_ADMIN_ENV_NAME = "TNS_ADMIN"
ORACLE_CONFIG_DIR_ENV_NAME = "ORACLE_CONFIG_DIR"
ORACLE_WALLET_PASSWORD_ENV_NAME = "ORACLE_WALLET_PASSWORD"

# 경로 설정
DEFAULT_ENCODING = "utf-8"
OUTPUT_DIR = BASE_DIR / "output"
BOOKS_DIR = BASE_DIR / "books"
RULEBOOK_DIR = BASE_DIR / "rulebook"
WORLDVIEW_DIR = BASE_DIR / "worldview"

# 문서/요청 유형 상수
DOCUMENT_TYPE_RULEBOOK = "RULEBOOK"
DOCUMENT_TYPE_WORLDVIEW = "WORLDVIEW"

REQUEST_TYPE_RULEBOOK_QA = "RULEBOOK_QA"
REQUEST_TYPE_WORLDVIEW_EXPLAIN = "WORLDVIEW_EXPLAIN"
